### ISSUE TITLE
It doesn't seem possible to register

### ISSUE THREAD

**Issue by waldyrious** [hugopeixoto/hacktoberfest-dashboard#2]
If I input my username and click "register", I get to this error page in https://hacktoberfest.hugopeixoto.net/register:

![Screenshot 2020-10-24 at 14 43 48](https://user-images.githubusercontent.com/478237/97083385-819c0500-1607-11eb-9a7a-8530626ced73.png)

**Comment by hugopeixoto** [comment]
Checking, thanks for reporting. I had to change the code a lot to consider the new rules, so I probably broke something.

**Comment by hugopeixoto** [comment]
Done :) your username was already registered, so you don't need to register again.
